version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /home/pi/.acme.sh/goooooouwa.tk/:/certs
    ports:
      - 8080:80
    restart: unless-stopped
