version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
    volumes:
      - /home/pi/.acme.sh/goooooouwa.fun/:/certs
    ports:
      - 8095:443
    restart: unless-stopped
