version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ~/.acme.sh/goooooouwa.tk/:/etc/letsencrypt/
    ports:
      - 8080:80
    restart: unless-stopped
